name: CI

on:
  push: 
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install nim
        uses: iffy/install-nim@v4
        with:
          version: binary:1.6.8

      - name: Build
        run: |
          ./scripts.sh ci_build

      - name: Upload build results
        uses: actions/upload-artifact@v3
        with:
          name: tg-to-pocket-${{ matrix.os }}
          path: build/*
          retention-days: 5
